server:
  port: 9000

spring:
  application:
    name: cravebyte-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cravebyte
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


